service: sendcsv
image: tjmr/sendcsv
servers:
  web:
    - app.sendcsv.com
proxy:
  ssl: true
  host: app.sendcsv.com
registry:
  server: localhost:5555
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    WEB_CONCURRENCY: auto
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "sendcsv_storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: amd64
